FROM python:latest

RUN python manage.py makemigrations && python manage.py migrate

WORKDIR /Django/DjangoAPI
COPY requirements.txt /Django/DjangoAPI
RUN pip install -r requirements.txt

EXPOSE 8000
CMD ["python", "manage.py", "runserver", '0.0.0.0:8000']
