# Generated by Django 3.2.4 on 2021-10-17 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestProject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter user name', max_length=30, unique=True)),
                ('description', models.TextField(help_text='Enter a description of the group', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter user name', max_length=30, unique=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(help_text='Select a group for this user', on_delete=django.db.models.deletion.PROTECT, to='TestProject.group')),
            ],
        ),
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
