# Generated by Django 3.2.4 on 2021-10-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestProject', '0002_auto_20211017_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
